"""empty message

Revision ID: 127fd7557ecb
Revises: 
Create Date: 2023-12-31 17:36:24.042816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127fd7557ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable='This is a description'))
        op.execute("UPDATE items SET description = 'This is a description'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
